### ISSUE TITLE
여러 alice demo를 동시에 수행 할 때 revocation registry 관련 에러 발생

### ISSUE THREAD

**Issue by baegjae** [sktston/aries-cloudagent-python#19]
### 상황
- 1 cloud agent (multitenant enabled) 에서
- 하나의 faber에 여러 alice demo를 동시에 수행 시
- revocation registry 관련 에러 발생

### 예상
- revocation registry maximum number 를 넘어서는 경우,
- 새로운 revocation registry를 추가 등록하게 되는데, 추가 등록이 제대로 이루어지지 않아 발생하는 것으로 판단하고 있음

### 계획
- test case의 범위를 좁혀서, 문제점 파악 요구

### 로그
```
acapy-agent-2_1  |
acapy-agent-2_1  | During handling of the above exception, another exception occurred:
acapy-agent-2_1  |
acapy-agent-2_1  | Traceback (most recent call last):
acapy-agent-2_1  |   File "/home/indy/aries_cloudagent/core/dispatcher.py", line 187, in handle_message
acapy-agent-2_1  |     await handler(context, responder)
acapy-agent-2_1  |   File "/home/indy/aries_cloudagent/protocols/issue_credential/v1_0/handlers/credential_request_handler.py", line 62, in handle
acapy-agent-2_1  |     cred_ex_record=cred_ex_record, comment=context.message.comment
acapy-agent-2_1  |   File "/home/indy/aries_cloudagent/protocols/issue_credential/v1_0/manager.py", line 567, in issue_credential
acapy-agent-2_1  |     retries=retries - 1,
acapy-agent-2_1  |   File "/home/indy/aries_cloudagent/protocols/issue_credential/v1_0/manager.py", line 567, in issue_credential
acapy-agent-2_1  |     retries=retries - 1,
acapy-agent-2_1  |   File "/home/indy/aries_cloudagent/protocols/issue_credential/v1_0/manager.py", line 567, in issue_credential
acapy-agent-2_1  |     retries=retries - 1,
acapy-agent-2_1  |   [Previous line repeated 2 more times]
acapy-agent-2_1  |   File "/home/indy/aries_cloudagent/protocols/issue_credential/v1_0/manager.py", line 571, in issue_credential
acapy-agent-2_1  |     f"Cred def id {cred_ex_record.credential_definition_id} "
acapy-agent-2_1  | aries_cloudagent.protocols.issue_credential.v1_0.manager.CredentialManagerError: Cred def id 7H55ZhRr97j62g8KY7TSyg:3:CL:171:tag.95.15.32 has no active revocation registry
acapy-agent-2_1  | 2021-01-12 08:54:02,335 aries_cloudagent.core.conductor ERROR DON'T shutdown on CredentialManagerError Cred def id 7H55ZhRr97j62g8KY7TSyg:3:CL:171:tag.95.15.32 has no active revocation registry
acapy-agent-2_1  | 2021-01-12 08:54:02,336 aries_cloudagent.core.dispatcher ERROR Handler error: Dispatcher.handle_message
acapy-agent-2_1  | Traceback (most recent call last):
acapy-agent-2_1  |   File "/home/indy/aries_cloudagent/protocols/issue_credential/v1_0/manager.py", line 518, in issue_credential
acapy-agent-2_1  |     cred_ex_record.credential_definition_id
acapy-agent-2_1  |   File "/home/indy/aries_cloudagent/revocation/indy.py", line 78, in get_active_issuer_rev_reg_record
acapy-agent-2_1  |     f"No active issuer revocation record found for cred def id {cred_def_id}"
acapy-agent-2_1  | aries_cloudagent.storage.error.StorageNotFoundError: No active issuer revocation record found for cred def id 7H55ZhRr97j62g8KY7TSyg:3:CL:171:tag.95.15.32
acapy-agent-2_1  |
```

**Comment by baegjae** [comment]
tails file을 생성하고 tails-server 에 업로드하는데 2초 timeout으로 5회 시도하게 되어 있음
https://github.com/sktston/aries-cloudagent-python/blob/ce0603eb3d47b3c9086700649e694c6ff683f18c/aries_cloudagent/protocols/issue_credential/v1_0/manager.py#L562

await asyncio.sleep(2) 시간을 조정하고, max_attempts=3 을 조정하면 여유 있게 성공할 수 있음 - 실험으로 확인
하지만, 해당 에러는 local PC에서 실험 시 발생하였던 현상이고, 아직까지 platform에서는 이러한 현상이 없었음.
추후 이러한 현상이 발생 시, 위 configuration을 조정하여 대응해야할 필요성이 있음.
